### ISSUE TITLE
The loottables dont work in 1.20.4

### ISSUE THREAD

**Issue by timtijmen2** [Triton365/BlockState#1]
The pack doesnt when i play on 1.20.4 but it does in 1.20.2

Console gives this error:
`Couldn't parse element loot_tables:blockstate:get - Not a json array: {"condition":"location_check","predicate":{"block":{"blocks":["yellow_candle","red_candle","birch_fence","light_blue_banner","green_banner","brown_concrete","quartz_block","purple_stained_glass","purple_concrete_powder","potted_wither_rose","potted_white_tulip","orange_stained_glass","orange_concrete_powder","dead_tube_coral","dead_horn_coral_fan","polished_blackstone_pressure_plate","oak_pressure_plate","hanging_roots","fire_coral_fan","sweet_berry_bush","nether_wart","dead_bubble_coral_fan","dead_bubble_coral","spruce_sign","dark_oak_fence","jungle_sign","warped_sign","brewing_stand","light_blue_concrete","cyan_stained_glass","bubble_coral_block","tube_coral_block","amethyst_block","spruce_planks","spore_blossom","kelp_plant","lava","bamboo_fence","potatoes","gravel","potted_warped_roots","potted_warped_fungus","grass","potted_pink_tulip","gold_block","potted_oak_sapling","potted_mangrove_propagule","farmland","acacia_pressure_plate","gilded_blackstone","copper_ore","flower_pot","potted_crimson_fungus","potted_cornflower","fletching_table","brown_banner","magenta_banner","mangrove_hanging_sign","cherry_hanging_sign","cherry_sign","blue_stained_glass_pane","daylight_detector","fern","cobblestone","mycelium","jungle_pressure_plate","dark_oak_pressure_plate","budding_amethyst","black_wool","cyan_terracotta","warped_fungus","terracotta","structure_void","black_terracotta","bamboo_mosaic","white_candle_cake","redstone_torch","pink_stained_glass","pink_concrete_powder","redstone_ore","light_gray_candle_cake","light_blue_candle_cake","orange_wool","dirt_path","dirt","chiseled_sandstone","mushroom_stem","oak_fence","purple_stained_glass_pane","chorus_plant","crimson_sign","tnt","cornflower","brain_coral_block","allium","acacia_planks","torchflower_crop","grass_block","potted_birch_sapling","potted_bamboo","potted_acacia_sapling","end_stone_bricks","end_stone","coarse_dirt","potted_azalea_bush","exposed_copper","frogspawn","potted_dead_bush","bubble_column","copper_block","bookshelf","carrots","light_gray_banner","candle","blue_banner","red_candle_cake","purple_candle_cake","lime_candle_cake","cobweb","potted_cherry_sapling","deepslate_redstone_ore","candle_cake","diorite","orange_concrete","bamboo_pressure_plate","skeleton_skull","acacia_sign","gray_candle","green_candle","cyan_candle","gray_banner","acacia_hanging_sign","spruce_hanging_sign","oak_hanging_sign","green_stained_glass_pane","white_stained_glass_pane","red_stained_glass_pane","wither_skeleton_skull","mangrove_sign","yellow_stained_glass_pane","jungle_fence","lime_stained_glass_pane","crimson_hanging_sign","yellow_banner","purple_banner","pumpkin_stem","deepslate_lapis_ore","nether_quartz_ore","chiseled_polished_blackstone","blue_concrete_powder","blue_concrete","bamboo_sapling","exposed_cut_copper","potted_azure_bluet","red_carpet","green_concrete_powder","dragon_egg","chiseled_stone_bricks","gray_terracotta","cracked_stone_bricks","warped_pressure_plate","blue_orchid","oxeye_daisy","orange_tulip","orange_terracotta","raw_gold_block","green_concrete","green_carpet","crafting_table","warped_hanging_sign","white_banner","crying_obsidian","sandstone","lilac","red_tulip","red_terracotta","brown_mushroom","redstone_block","brain_coral_fan","brain_coral","dark_oak_planks","calcite","dandelion","waxed_exposed_cut_copper","black_stained_glass_pane","jungle_hanging_sign","red_mushroom_block","glow_lichen"]}}}; Not a json array: {"condition":"location_check","predicate":{"block":{"blocks":["yellow_candle","red_candle","birch_fence","light_blue_banner","green_banner","brown_concrete","quartz_block","purple_stained_glass","purple_concrete_powder","potted_wither_rose","potted_white_tulip","orange_stained_glass","orange_concrete_powder","dead_tube_coral","dead_horn_coral_fan","polished_blackstone_pressure_plate","oak_pressure_plate","hanging_roots","fire_coral_fan","sweet_berry_bush","nether_wart","dead_bubble_coral_fan","dead_bubble_coral","spruce_sign","dark_oak_fence","jungle_sign","warped_sign","brewing_stand","light_blue_concrete","cyan_stained_glass","bubble_coral_block","tube_coral_block","amethyst_block","spruce_planks","spore_blossom","kelp_plant","lava","bamboo_fence","potatoes","gravel","potted_warped_roots","potted_warped_fungus","grass","potted_pink_tulip","gold_block","potted_oak_sapling","potted_mangrove_propagule","farmland","acacia_pressure_plate","gilded_blackstone","copper_ore","flower_pot","potted_crimson_fungus","potted_cornflower","fletching_table","brown_banner","magenta_banner","mangrove_hanging_sign","cherry_hanging_sign","cherry_sign","blue_stained_glass_pane","daylight_detector","fern","cobblestone","mycelium","jungle_pressure_plate","dark_oak_pressure_plate","budding_amethyst","black_wool","cyan_terracotta","warped_fungus","terracotta","structure_void","black_terracotta","bamboo_mosaic","white_candle_cake","redstone_torch","pink_stained_glass","pink_concrete_powder","redstone_ore","light_gray_candle_cake","light_blue_candle_cake","orange_wool","dirt_path","dirt","chiseled_sandstone","mushroom_stem","oak_fence","purple_stained_glass_pane","chorus_plant","crimson_sign","tnt","cornflower","brain_coral_block","allium","acacia_planks","torchflower_crop","grass_block","potted_birch_sapling","potted_bamboo","potted_acacia_sapling","end_stone_bricks","end_stone","coarse_dirt","potted_azalea_bush","exposed_copper","frogspawn","potted_dead_bush","bubble_column","copper_block","bookshelf","carrots","light_gray_banner","candle","blue_banner","red_candle_cake","purple_candle_cake","lime_candle_cake","cobweb","potted_cherry_sapling","deepslate_redstone_ore","candle_cake","diorite","orange_concrete","bamboo_pressure_plate","skeleton_skull","acacia_sign"]}}}; Not a json array: {"condition":"location_check","predicate":{"block":{"blocks":["yellow_candle","red_candle","birch_fence","light_blue_banner","green_banner","brown_concrete","quartz_block","purple_stained_glass","purple_concrete_powder","potted_wither_rose","potted_white_tulip","orange_stained_glass","orange_concrete_powder","dead_tube_coral","dead_horn_coral_fan","polished_blackstone_pressure_plate","oak_pressure_plate","hanging_roots","fire_coral_fan","sweet_berry_bush","nether_wart","dead_bubble_coral_fan","dead_bubble_coral","spruce_sign","dark_oak_fence","jungle_sign","warped_sign","brewing_stand","light_blue_concrete","cyan_stained_glass","bubble_coral_block","tube_coral_block","amethyst_block","spruce_planks","spore_blossom","kelp_plant","lava","bamboo_fence","potatoes","gravel","potted_warped_roots","potted_warped_fungus","grass","potted_pink_tulip","gold_block","potted_oak_sapling","potted_mangrove_propagule","farmland","acacia_pressure_plate","gilded_blackstone","copper_ore","flower_pot","potted_crimson_fungus","potted_cornflower","fletching_table","brown_banner","magenta_banner","mangrove_hanging_sign","cherry_hanging_sign"]}}}; Not a json array: {"condition":"location_check","predicate":{"block":{"blocks":["brewing_stand","light_blue_concrete","cyan_stained_glass","bubble_coral_block","tube_coral_block","amethyst_block","spruce_planks","spore_blossom","kelp_plant","lava","bamboo_fence","potatoes","gravel","potted_warped_roots","potted_warped_fungus","grass","potted_pink_tulip","gold_block","potted_oak_sapling","potted_mangrove_propagule","farmland","acacia_pressure_plate","gilded_blackstone","copper_ore","flower_pot","potted_crimson_fungus","potted_cornflower","fletching_table","brown_banner","magenta_banner"]}}}; Not a json array: {"condition":"location_check","predicate":{"block":{"blocks":["potatoes","gravel","potted_warped_roots","potted_warped_fungus","grass","potted_pink_tulip","gold_block","potted_oak_sapling","potted_mangrove_propagule","farmland","acacia_pressure_plate","gilded_blackstone","copper_ore","flower_pot","potted_crimson_fungus","potted_cornflower","fletching_table"]}}}; Not a json array: {"condition":"location_check","predicate":{"block":{"blocks":["potatoes","gravel","potted_warped_roots","potted_warped_fungus","grass","potted_pink_tulip","gold_block","potted_oak_sapling","potted_mangrove_propagule"]}}}; Not a json array: {"condition":"location_check","predicate":{"block":{"blocks":["gravel","potted_warped_roots","potted_warped_fungus","grass"]}}}`

**Comment by Triton365** [comment]
`grass` got renamed to `short_grass` after 1.20.3 update so this would be the problem (...maybe)
This pack is very vulnerable to this type of update because it hardcodes all block IDs for that specific version, so don't forget to update it whenever new blocks get added or any block IDs change.

You can download 1.20.3 pack here, it works on both 1.20.3 and 1.20.4
https://github.com/Triton365/BlockState/releases/download/v1.0.1/BlockState_1.20.3.zip
